language: csharp
dist: xenial

sudo: false

env:
  global:
    - HOME=/home/travis
    - APPDATA=/home/travis
    - LocalAppData=/home/travis
  matrix:
    # run .net integration tests
    - SkipIntegrationTestsNetCore=true PAKET_TESTSUITE_FLAKYTESTS=false
    # run .net core integration tests
    - SkipIntegrationTestsNet=true PAKET_TESTSUITE_FLAKYTESTS=false
    # just flaky tests
    - PAKET_TESTSUITE_FLAKYTESTS=true

dotnet: 5.0.300

mono:
  - 5.18.1
  - 5.16.0
  - latest

matrix:
  allow_failures:
    # fake fails, ref https://github.com/fsharp/FAKE/issues/2362
    - mono: latest
    # flaky test are expected to fail from time to time
    - env: PAKET_TESTSUITE_FLAKYTESTS=true
    # sporadic MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
    - env: SkipIntegrationTestsNetCore=true PAKET_TESTSUITE_FLAKYTESTS=false

branches:
  except:
    - gh-pages

script:
  # the `< /dev/null` workaround for dotnet test hang (ref https://github.com/microsoft/vstest/issues/2080#issuecomment-539879345 )
  - ./build.sh BuildPackage < /dev/null
